#!/usr/bin/env python
import gtk
import sys

# comment-out if CodeBuffer is installed
from lib.codebuffer import CodeBuffer, SyntaxLoader, add_syntax_path


# comment-out if CodeBuffer is installed
add_syntax_path("data/syntax")

lang = SyntaxLoader("arduino")
buff = CodeBuffer(lang=lang)

win = gtk.Window(gtk.WINDOW_TOPLEVEL)
scr = gtk.ScrolledWindow()
win.add(scr)
scr.add(gtk.TextView(buff))

win.set_default_size(300,200)
win.show_all()
win.connect("destroy", lambda w: gtk.main_quit())

buff.set_text(open('data/examples/Stubs/HelloWorld/HelloWorld.pde','r').read())
 
gtk.main()
